services:
  web:
    build: .
    container_name: salonsphere-dev
    ports:
      - "3001:3000"
    volumes:
      # Mount de broncode voor hot-reloading
      - .:/app
      # Gebruik de node_modules uit de container, niet van de host
      - /app/node_modules
      # Gebruik de .next build folder uit de container
      - /app/.next
    environment:
      # Nodig voor file watching (hot-reload) in Docker
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    command: npm run dev -- -H 0.0.0.0 